#!/usr/bin/env bash
# H200 Mini-o3 PyVision-style train profile on official verl.

set -xeuo pipefail

PROJECT_DIR=${PROJECT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}

export HF_HOME=${HF_HOME:-/mnt/localssd/hf-cache}
export WANDB_MODE=${WANDB_MODE:-online}
export TOKENIZERS_PARALLELISM=${TOKENIZERS_PARALLELISM:-false}
export HYDRA_FULL_ERROR=${HYDRA_FULL_ERROR:-1}
export VLLM_USE_V1=${VLLM_USE_V1:-1}
export KEEP_ASYNC_ROLLOUT_AWAKE_DURING_GENERATION=${KEEP_ASYNC_ROLLOUT_AWAKE_DURING_GENERATION:-True}
export GLOBAL_READY_TURN_MAX_INFLIGHT=${GLOBAL_READY_TURN_MAX_INFLIGHT:-128}
export GLOBAL_ACTIVE_TRAJECTORY_MAX=${GLOBAL_ACTIVE_TRAJECTORY_MAX:-$((GLOBAL_READY_TURN_MAX_INFLIGHT * 4))}

DATA_DIR=${DATA_DIR:-$PROJECT_DIR/data/minio3_real_train_h200}
PROFILE=h200 DATA_DIR="$DATA_DIR" bash "$PROJECT_DIR/examples/minio3/prepare_real_train_data.sh"

if [[ -z "${LORA_TARGET_MODULES:-}" ]]; then
    LORA_TARGET_MODULES='.*model\.layers\..*(q_proj|k_proj|v_proj|o_proj|gate_proj|up_proj|down_proj)$'
fi
export LORA_TARGET_MODULES

CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7} \
MODEL_PATH=${MODEL_PATH:-Mini-o3/Mini-o3-7B-SFT} \
TRAIN_FILE=${TRAIN_FILE:-$DATA_DIR/train.parquet} \
VAL_FILE=${VAL_FILE:-$DATA_DIR/val.parquet} \
RUN_DIR=${RUN_DIR:-$PROJECT_DIR/save/lora_pyvision_style_h200} \
TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE:-64} \
VAL_BATCH_SIZE=${VAL_BATCH_SIZE:-32} \
PPO_MINI_BATCH_SIZE=${PPO_MINI_BATCH_SIZE:-16} \
PPO_MICRO_BATCH_SIZE_PER_GPU=${PPO_MICRO_BATCH_SIZE_PER_GPU:-4} \
LOG_PROB_MICRO_BATCH_SIZE_PER_GPU=${LOG_PROB_MICRO_BATCH_SIZE_PER_GPU:-16} \
REF_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU=${REF_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU:-16} \
USE_DYNAMIC_BSZ=${USE_DYNAMIC_BSZ:-False} \
MAX_PROMPT_LENGTH=${MAX_PROMPT_LENGTH:-8192} \
MAX_RESPONSE_LENGTH=${MAX_RESPONSE_LENGTH:-16384} \
VAL_RESPONSE_LENGTH=${VAL_RESPONSE_LENGTH:-32768} \
MAX_MODEL_LEN=${MAX_MODEL_LEN:-40960} \
ROLLOUT_TP=${ROLLOUT_TP:-1} \
ROLLOUT_GPU_MEM_UTIL=${ROLLOUT_GPU_MEM_UTIL:-0.9} \
MAX_NUM_BATCHED_TOKENS=${MAX_NUM_BATCHED_TOKENS:-32768} \
MAX_NUM_SEQS=${MAX_NUM_SEQS:-256} \
ROLLOUT_N=${ROLLOUT_N:-8} \
AGENT_NUM_WORKERS=${AGENT_NUM_WORKERS:-128} \
MAX_ASSISTANT_TURNS=${MAX_ASSISTANT_TURNS:-6} \
MAX_USER_TURNS=${MAX_USER_TURNS:-6} \
VAL_MAX_ASSISTANT_TURNS=${VAL_MAX_ASSISTANT_TURNS:-12} \
VAL_MAX_USER_TURNS=${VAL_MAX_USER_TURNS:-12} \
VAL_N=${VAL_N:-1} \
VAL_DO_SAMPLE=${VAL_DO_SAMPLE:-True} \
VAL_TEMPERATURE=${VAL_TEMPERATURE:-1.0} \
ACTOR_PARAM_OFFLOAD=${ACTOR_PARAM_OFFLOAD:-True} \
ACTOR_OPTIMIZER_OFFLOAD=${ACTOR_OPTIMIZER_OFFLOAD:-True} \
REF_PARAM_OFFLOAD=${REF_PARAM_OFFLOAD:-True} \
LORA_RANK=${LORA_RANK:-8} \
LORA_ALPHA=${LORA_ALPHA:-16} \
ACTOR_LR=${ACTOR_LR:-1e-6} \
USE_KL_LOSS=${USE_KL_LOSS:-False} \
KL_LOSS_COEF=${KL_LOSS_COEF:-0.000} \
ENTROPY_COEFF=${ENTROPY_COEFF:-0.000} \
CLIP_RATIO_HIGH=${CLIP_RATIO_HIGH:-0.3} \
CLIP_RATIO_LOW=${CLIP_RATIO_LOW:-0.2} \
MAX_NUM_GEN_BATCHES=${MAX_NUM_GEN_BATCHES:-256} \
TOTAL_EPOCHS=${TOTAL_EPOCHS:-100} \
TOTAL_TRAINING_STEPS=${TOTAL_TRAINING_STEPS:-1} \
SAVE_FREQ=${SAVE_FREQ:-10} \
SAVE_LORA_ONLY=${SAVE_LORA_ONLY:-True} \
TEST_FREQ=${TEST_FREQ:-5} \
LOG_VAL_GENERATIONS=${LOG_VAL_GENERATIONS:-512} \
VAL_BEFORE_TRAIN=${VAL_BEFORE_TRAIN:-False} \
VAL_ONLY=${VAL_ONLY:-False} \
NGPUS_PER_NODE=${NGPUS_PER_NODE:-8} \
PROJECT_NAME=${PROJECT_NAME:-Mini-o3} \
EXPERIMENT_NAME=${EXPERIMENT_NAME:-Mini-o3-RL-LoRA-pyvision-style-h200} \
bash "$PROJECT_DIR/examples/minio3/run_qwen3_vl_8b_crop_lora_fsdp.sh" "$@"
