#!/usr/bin/env bash
# Qwen3.5-9B official-tool Mini-o3 RL profile for the local 8x H200 node.

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
SCRIPT_PATH="$SCRIPT_DIR/$(basename "${BASH_SOURCE[0]}")"
PROJECT_DIR=${PROJECT_DIR:-$(cd "$SCRIPT_DIR/../.." && pwd)}
MODE=${1:-formal}
if (($# > 0)); then
  shift
fi
TIMESTAMP=${TIMESTAMP:-$(date +%Y%m%d_%H%M%S)}

LOCAL_QWEN35_SNAPSHOT=/mnt/localssd/.cache/huggingface/hub/models--Qwen--Qwen3.5-9B/snapshots/c202236235762e1c871ad0ccb60c8ee5ba337b9a
if [[ -z "${MODEL_PATH:-}" ]]; then
  if [[ -d "$LOCAL_QWEN35_SNAPSHOT" ]]; then
    MODEL_PATH="$LOCAL_QWEN35_SNAPSHOT"
  else
    MODEL_PATH=Qwen/Qwen3.5-9B
  fi
fi

case "$MODE" in
  formal)
    RUN_PREFIX=${RUN_PREFIX:-qwen35_9b_official_tool_h200_rl}
    ;;
  smoke)
    RUN_PREFIX=${RUN_PREFIX:-qwen35_9b_official_tool_h200_rl_smoke}
    ;;
  *)
    echo "usage: $0 [formal|smoke]" >&2
    exit 2
    ;;
esac

USER_FORWARD_VARS=(
  WANDB_MODE OMP_NUM_THREADS MKL_NUM_THREADS OPENBLAS_NUM_THREADS NUMEXPR_NUM_THREADS \
  TRAIN_BATCH_SIZE VAL_BATCH_SIZE PPO_MINI_BATCH_SIZE \
  PPO_MICRO_BATCH_SIZE_PER_GPU LOG_PROB_MICRO_BATCH_SIZE_PER_GPU \
  REF_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU MAX_RESPONSE_LENGTH VAL_RESPONSE_LENGTH \
  MAX_MODEL_LEN MAX_NUM_BATCHED_TOKENS MAX_NUM_SEQS ROLLOUT_N AGENT_NUM_WORKERS \
  MINIO3_TOOL_PROMPT_SUITE MINIO3_OFFICIAL_TOOL_NAME MINIO3_AGENT_LOOP ROLLOUT_AGENT_LOOP \
  ROLLOUT_MULTI_TURN_FORMAT ADD_VISION_ID \
  MAX_ASSISTANT_TURNS MAX_USER_TURNS VAL_MAX_ASSISTANT_TURNS VAL_MAX_USER_TURNS \
  VAL_N VAL_DO_SAMPLE VAL_TEMPERATURE VAL_TOP_P VAL_TOP_K \
  TOTAL_TRAINING_STEPS SAVE_FREQ SAVE_LORA_ONLY TEST_FREQ LOG_VAL_GENERATIONS \
  VAL_BEFORE_TRAIN VAL_ONLY SELF_JUDGE_REWARD \
  MINIO3_IGNORE_CLIP MINIO3_IGNORE_EXCEED MINIO3_IGNORE_FORMAT MINIO3_IGNORE_INVALID \
  PROMPT_ADMISSION_ENABLE PROMPT_ADMISSION_POOL_SIZE LOGGER_BACKENDS TRAIN_MAX_SAMPLES VAL_MAX_SAMPLES \
  DATALOADER_NUM_WORKERS FILTER_OVERLONG_PROMPTS_WORKERS PROJECT_NAME EXPERIMENT_NAME RAY_NUM_CPUS ROLLOUT_DP ROLLOUT_TP \
  ROLLOUT_GPU_MEM_UTIL ACTOR_LR USE_KL_LOSS KL_LOSS_COEF ENTROPY_COEFF \
  CLIP_RATIO_HIGH CLIP_RATIO_LOW LORA_RANK LORA_ALPHA LORA_TARGET_MODULES \
  MINIO3_RAY_STARTUP_RETRIES MINIO3_RAY_STARTUP_RETRY_DELAY_S
)

declare -A USER_SET
for var_name in "${USER_FORWARD_VARS[@]}"; do
  if [[ -v "$var_name" ]]; then
    USER_SET[$var_name]=1
  fi
done

set_mode_default() {
  local name=$1
  local value=$2
  if [[ -z "${USER_SET[$name]:-}" ]]; then
    export "$name=$value"
  fi
}

RUN_ID=${RUN_ID:-${RUN_PREFIX}_${TIMESTAMP}}
RUN_DIR=${RUN_DIR:-$PROJECT_DIR/save/$RUN_ID}
LOG_PATH=${LOG_PATH:-$PROJECT_DIR/logs/$RUN_ID.log}
TMUX_SESSION=${TMUX_SESSION:-minio3_${MODE}_${TIMESTAMP}}

if [[ "${MINIO3_PRINT_CONFIG_ONLY:-0}" == "1" ]]; then
  export MINIO3_TRAIN_FOREGROUND=1
fi

if [[ "${MINIO3_TRAIN_FOREGROUND:-0}" != "1" && "${MINIO3_TRAIN_INNER:-0}" != "1" ]]; then
  mkdir -p "$PROJECT_DIR/logs" "$RUN_DIR"
  LAUNCH_ENV_PATH="$RUN_DIR/launch_env.sh"
  : > "$LAUNCH_ENV_PATH"
  chmod 600 "$LAUNCH_ENV_PATH"
  for var_name in "${USER_FORWARD_VARS[@]}"; do
    if [[ -n "${USER_SET[$var_name]:-}" ]]; then
      printf 'export %s=%q\n' "$var_name" "${!var_name}" >> "$LAUNCH_ENV_PATH"
    fi
  done
  printf -v cmd 'cd %q && source %q && MINIO3_TRAIN_INNER=1 RUN_ID=%q RUN_DIR=%q LOG_PATH=%q MODEL_PATH=%q bash %q %q > %q 2>&1' \
    "$PROJECT_DIR" "$LAUNCH_ENV_PATH" "$RUN_ID" "$RUN_DIR" "$LOG_PATH" "$MODEL_PATH" "$SCRIPT_PATH" "$MODE" "$LOG_PATH"
  tmux new-session -d -s "$TMUX_SESSION" "$cmd"
  echo "launched tmux session: $TMUX_SESSION"
  echo "log: $LOG_PATH"
  echo "run dir: $RUN_DIR"
  echo "launch env: $LAUNCH_ENV_PATH"
  exit 0
fi

AGENTS_FILE=${AGENTS_FILE:-/mnt/localssd/AGENTS.md}
if [[ -z "${DEEPSEEK_API_KEY:-}" && -r "$AGENTS_FILE" ]]; then
  DEEPSEEK_API_KEY=$(grep -o 'sk-[A-Za-z0-9]*' "$AGENTS_FILE" | tail -n 1 || true)
fi
if [[ -z "${HF_TOKEN:-}" && -r "$AGENTS_FILE" ]]; then
  HF_TOKEN=$(grep -o 'hf_[A-Za-z0-9]*' "$AGENTS_FILE" | head -n 1 || true)
fi
if [[ "$MODE" == "smoke" ]]; then
  set_mode_default SELF_JUDGE_REWARD False
fi
if [[ "${SELF_JUDGE_REWARD:-True}" == "True" && -z "${DEEPSEEK_API_KEY:-}" ]]; then
  echo "missing DEEPSEEK_API_KEY; export it or provide $AGENTS_FILE" >&2
  exit 2
fi
if [[ -n "${DEEPSEEK_API_KEY:-}" ]]; then
  export DEEPSEEK_API_KEY
fi
if [[ -n "${HF_TOKEN:-}" ]]; then
  export HF_TOKEN HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN:-$HF_TOKEN}
fi

if [[ "$MODEL_PATH" == /* ]]; then
  export HF_HUB_OFFLINE=${HF_HUB_OFFLINE:-1}
  export TRANSFORMERS_OFFLINE=${TRANSFORMERS_OFFLINE:-1}
fi

export PROJECT_DIR MODEL_PATH RUN_ID RUN_DIR
export PYTHON_CMD=${PYTHON_CMD:-"uv run --project $PROJECT_DIR --no-sync python"}
export HF_HOME=${HF_HOME:-/mnt/localssd/.cache/huggingface}
export WANDB_MODE=${WANDB_MODE:-online}
export TOKENIZERS_PARALLELISM=${TOKENIZERS_PARALLELISM:-false}
export OMP_NUM_THREADS=${OMP_NUM_THREADS:-1}
export MKL_NUM_THREADS=${MKL_NUM_THREADS:-1}
export OPENBLAS_NUM_THREADS=${OPENBLAS_NUM_THREADS:-1}
export NUMEXPR_NUM_THREADS=${NUMEXPR_NUM_THREADS:-1}
export HYDRA_FULL_ERROR=${HYDRA_FULL_ERROR:-1}
export VLLM_USE_V1=${VLLM_USE_V1:-1}
export MINIO3_STAGE_LOG=${MINIO3_STAGE_LOG:-1}
export MINIO3_TRAJ_STATUS_INTERVAL_S=${MINIO3_TRAJ_STATUS_INTERVAL_S:-15}
export MINIO3_RAY_STARTUP_RETRIES=${MINIO3_RAY_STARTUP_RETRIES:-2}
export MINIO3_RAY_STARTUP_RETRY_DELAY_S=${MINIO3_RAY_STARTUP_RETRY_DELAY_S:-15}

export MINIO3_TOOL_PROMPT_SUITE=${MINIO3_TOOL_PROMPT_SUITE:-qwen35_official_zoom_tool_final_sentence}
export MINIO3_OFFICIAL_TOOL_NAME=${MINIO3_OFFICIAL_TOOL_NAME:-image_zoom_in_tool}
export MINIO3_AGENT_LOOP=${MINIO3_AGENT_LOOP:-mini_o3_tool_agent}
export ROLLOUT_AGENT_LOOP=${ROLLOUT_AGENT_LOOP:-mini_o3_tool_agent}
export ROLLOUT_MULTI_TURN_FORMAT=${ROLLOUT_MULTI_TURN_FORMAT:-qwen3_coder}

export MAX_PROMPT_LENGTH=${MAX_PROMPT_LENGTH:-16384}
export MAX_RESPONSE_LENGTH=${MAX_RESPONSE_LENGTH:-16384}
export VAL_RESPONSE_LENGTH=${VAL_RESPONSE_LENGTH:-32768}
export MAX_MODEL_LEN=${MAX_MODEL_LEN:-65536}
export ROLLOUT_DISABLE_MM_PREPROCESSOR_CACHE=${ROLLOUT_DISABLE_MM_PREPROCESSOR_CACHE:-False}
export ROLLOUT_SKIP_VLLM_DUMMY_LORA=${ROLLOUT_SKIP_VLLM_DUMMY_LORA:-True}
export ROLLOUT_VLLM_EXECUTOR_BACKEND=${ROLLOUT_VLLM_EXECUTOR_BACKEND:-uni}
export ROLLOUT_DP=${ROLLOUT_DP:-8}
export ROLLOUT_TP=${ROLLOUT_TP:-1}
export ROLLOUT_GPU_MEM_UTIL=${ROLLOUT_GPU_MEM_UTIL:-0.9}
export MAX_NUM_BATCHED_TOKENS=${MAX_NUM_BATCHED_TOKENS:-65536}
export MAX_NUM_SEQS=${MAX_NUM_SEQS:-256}
export ROLLOUT_N=${ROLLOUT_N:-8}
export AGENT_NUM_WORKERS=${AGENT_NUM_WORKERS:-64}
export RAY_NUM_CPUS=${RAY_NUM_CPUS:-96}

export TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE:-64}
export VAL_BATCH_SIZE=${VAL_BATCH_SIZE:-512}
export TRAIN_MAX_SAMPLES=${TRAIN_MAX_SAMPLES:--1}
export VAL_MAX_SAMPLES=${VAL_MAX_SAMPLES:--1}
export FILTER_OVERLONG_PROMPTS_WORKERS=${FILTER_OVERLONG_PROMPTS_WORKERS:-16}
export PPO_MINI_BATCH_SIZE=${PPO_MINI_BATCH_SIZE:-16}
export PPO_MICRO_BATCH_SIZE_PER_GPU=${PPO_MICRO_BATCH_SIZE_PER_GPU:-2}
export LOG_PROB_MICRO_BATCH_SIZE_PER_GPU=${LOG_PROB_MICRO_BATCH_SIZE_PER_GPU:-16}
export REF_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU=${REF_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU:-16}
export USE_DYNAMIC_BSZ=${USE_DYNAMIC_BSZ:-False}
export ACTOR_PARAM_OFFLOAD=${ACTOR_PARAM_OFFLOAD:-True}
export ACTOR_OPTIMIZER_OFFLOAD=${ACTOR_OPTIMIZER_OFFLOAD:-True}
export REF_PARAM_OFFLOAD=${REF_PARAM_OFFLOAD:-True}
export LORA_RANK=${LORA_RANK:-8}
export LORA_ALPHA=${LORA_ALPHA:-16}
export ACTOR_LR=${ACTOR_LR:-1e-6}
export USE_KL_LOSS=${USE_KL_LOSS:-False}
export KL_LOSS_COEF=${KL_LOSS_COEF:-0.000}
export ENTROPY_COEFF=${ENTROPY_COEFF:-0.000}
export CLIP_RATIO_HIGH=${CLIP_RATIO_HIGH:-0.3}
export CLIP_RATIO_LOW=${CLIP_RATIO_LOW:-0.2}

export MAX_ASSISTANT_TURNS=${MAX_ASSISTANT_TURNS:-12}
export MAX_USER_TURNS=${MAX_USER_TURNS:-12}
export VAL_MAX_ASSISTANT_TURNS=${VAL_MAX_ASSISTANT_TURNS:-12}
export VAL_MAX_USER_TURNS=${VAL_MAX_USER_TURNS:-12}
export VAL_N=${VAL_N:-1}
export VAL_DO_SAMPLE=${VAL_DO_SAMPLE:-True}
export VAL_TEMPERATURE=${VAL_TEMPERATURE:-1.0}
export VAL_TOP_P=${VAL_TOP_P:-1.0}
export VAL_TOP_K=${VAL_TOP_K:--1}
export ADD_VISION_ID=${ADD_VISION_ID:-True}

export SELF_JUDGE_REWARD=${SELF_JUDGE_REWARD:-True}
export SELF_JUDGE_PROVIDER=${SELF_JUDGE_PROVIDER:-deepseek}
export SELF_JUDGE_MODEL=${SELF_JUDGE_MODEL:-deepseek-v4-flash}
export SELF_JUDGE_BASE_URL=${SELF_JUDGE_BASE_URL:-https://api.deepseek.com}
export SELF_JUDGE_REASONING_EFFORT=${SELF_JUDGE_REASONING_EFFORT:-none}
export SELF_JUDGE_MAX_TOKENS=${SELF_JUDGE_MAX_TOKENS:-8}
export SELF_JUDGE_TEMPERATURE=${SELF_JUDGE_TEMPERATURE:-0.0}
export SELF_JUDGE_MAX_RETRIES=${SELF_JUDGE_MAX_RETRIES:-5}
export SELF_JUDGE_TIMEOUT=${SELF_JUDGE_TIMEOUT:-60}
export SELF_JUDGE_INITIAL_DELAY=${SELF_JUDGE_INITIAL_DELAY:-1.0}
export SELF_JUDGE_RELAXED_ANSWER=${SELF_JUDGE_RELAXED_ANSWER:-True}

export MINIO3_IGNORE_CLIP=${MINIO3_IGNORE_CLIP:-False}
export MINIO3_IGNORE_EXCEED=${MINIO3_IGNORE_EXCEED:-False}
export MINIO3_IGNORE_FORMAT=${MINIO3_IGNORE_FORMAT:-False}
export MINIO3_IGNORE_INVALID=${MINIO3_IGNORE_INVALID:-False}
export PROMPT_ADMISSION_ENABLE=${PROMPT_ADMISSION_ENABLE:-True}
export PROMPT_ADMISSION_POOL_SIZE=${PROMPT_ADMISSION_POOL_SIZE:-160}
export PROMPT_ADMISSION_REWARD_STD_EPSILON=${PROMPT_ADMISSION_REWARD_STD_EPSILON:-1.0e-4}
export PROMPT_ADMISSION_WAIT_TIMEOUT_S=${PROMPT_ADMISSION_WAIT_TIMEOUT_S:-0.1}
export PROMPT_ADMISSION_CANCEL_UNFINISHED=${PROMPT_ADMISSION_CANCEL_UNFINISHED:-True}

export TOTAL_EPOCHS=${TOTAL_EPOCHS:-100}
export TOTAL_TRAINING_STEPS=${TOTAL_TRAINING_STEPS:-100}
export SAVE_FREQ=${SAVE_FREQ:-10}
export SAVE_LORA_ONLY=${SAVE_LORA_ONLY:-True}
export TEST_FREQ=${TEST_FREQ:-10}
export LOG_VAL_GENERATIONS=${LOG_VAL_GENERATIONS:-512}
export VAL_BEFORE_TRAIN=${VAL_BEFORE_TRAIN:-False}
export VAL_ONLY=${VAL_ONLY:-False}
export LOGGER_BACKENDS=${LOGGER_BACKENDS:-'["console","wandb","file"]'}
export PROJECT_NAME=${PROJECT_NAME:-Mini-o3-qwen35-rl}
export EXPERIMENT_NAME=${EXPERIMENT_NAME:-$RUN_ID}

if [[ "$MODE" == "smoke" ]]; then
  set_mode_default WANDB_MODE disabled
  set_mode_default TRAIN_BATCH_SIZE 8
  set_mode_default VAL_BATCH_SIZE 8
  set_mode_default TRAIN_MAX_SAMPLES 8
  set_mode_default VAL_MAX_SAMPLES 8
  set_mode_default DATALOADER_NUM_WORKERS 0
  set_mode_default PPO_MINI_BATCH_SIZE 8
  set_mode_default PPO_MICRO_BATCH_SIZE_PER_GPU 1
  set_mode_default LOG_PROB_MICRO_BATCH_SIZE_PER_GPU 1
  set_mode_default REF_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU 1
  set_mode_default MAX_RESPONSE_LENGTH 2048
  set_mode_default VAL_RESPONSE_LENGTH 2048
  set_mode_default MAX_MODEL_LEN 32768
  set_mode_default MAX_NUM_BATCHED_TOKENS 32768
  set_mode_default MAX_NUM_SEQS 64
  set_mode_default ROLLOUT_N 1
  set_mode_default AGENT_NUM_WORKERS 8
  set_mode_default TOTAL_TRAINING_STEPS 1
  set_mode_default SAVE_FREQ -1
  set_mode_default TEST_FREQ -1
  set_mode_default LOG_VAL_GENERATIONS 8
  set_mode_default PROMPT_ADMISSION_ENABLE False
  set_mode_default LOGGER_BACKENDS '["console","file"]'
fi

if [[ "${PROMPT_ADMISSION_ENABLE,,}" != "true" ]] && (( TRAIN_BATCH_SIZE % AGENT_NUM_WORKERS != 0 )); then
  echo "TRAIN_BATCH_SIZE must be divisible by AGENT_NUM_WORKERS for non-prompt-admission agent-loop rollout chunking: ${TRAIN_BATCH_SIZE} vs ${AGENT_NUM_WORKERS}" >&2
  exit 2
fi

if [[ "${MINIO3_PRINT_CONFIG_ONLY:-0}" == "1" ]]; then
  for name in \
    MODE RUN_ID RUN_DIR MODEL_PATH MINIO3_TOOL_PROMPT_SUITE MINIO3_OFFICIAL_TOOL_NAME \
    MINIO3_AGENT_LOOP ROLLOUT_MULTI_TURN_FORMAT TRAIN_BATCH_SIZE PPO_MINI_BATCH_SIZE \
    PPO_MICRO_BATCH_SIZE_PER_GPU \
    TRAIN_MAX_SAMPLES VAL_MAX_SAMPLES FILTER_OVERLONG_PROMPTS_WORKERS \
    ROLLOUT_N ROLLOUT_DP ROLLOUT_TP MAX_PROMPT_LENGTH MAX_RESPONSE_LENGTH \
    VAL_RESPONSE_LENGTH MAX_MODEL_LEN MAX_NUM_BATCHED_TOKENS MAX_NUM_SEQS \
    ADD_VISION_ID \
    MAX_ASSISTANT_TURNS MAX_USER_TURNS VAL_MAX_ASSISTANT_TURNS VAL_MAX_USER_TURNS \
    AGENT_NUM_WORKERS RAY_NUM_CPUS SELF_JUDGE_REWARD SELF_JUDGE_PROVIDER \
    SELF_JUDGE_MODEL SELF_JUDGE_RELAXED_ANSWER PROMPT_ADMISSION_ENABLE \
    MINIO3_IGNORE_CLIP MINIO3_IGNORE_EXCEED MINIO3_IGNORE_FORMAT MINIO3_IGNORE_INVALID \
    PROMPT_ADMISSION_POOL_SIZE \
    ACTOR_LR LORA_RANK LORA_ALPHA LORA_TARGET_MODULES \
    TOTAL_TRAINING_STEPS SAVE_FREQ TEST_FREQ LOGGER_BACKENDS WANDB_MODE \
    MINIO3_RAY_STARTUP_RETRIES MINIO3_RAY_STARTUP_RETRY_DELAY_S \
    OMP_NUM_THREADS MKL_NUM_THREADS OPENBLAS_NUM_THREADS NUMEXPR_NUM_THREADS; do
    printf '%s=%s\n' "$name" "${!name-}"
  done
  exit 0
fi

ray_startup_failure_seen() {
  local start_offset=${1:-0}
  [[ -n "${LOG_PATH:-}" && -f "$LOG_PATH" ]] || return 1
  tail -c "+$((start_offset + 1))" "$LOG_PATH" | grep -Eq \
    'Runtime Env Agent timed out|Raylet could not connect to Runtime Env Agent|Failed to register worker to Raylet|runtime_env_agent'
}

training_has_started() {
  [[ -s "$RUN_DIR/train_step_metrics.jsonl" ]] && return 0
  [[ -s "$RUN_DIR/train_samples.jsonl" ]] && return 0
  if [[ -d "$RUN_DIR/rollout_generations" ]] && find "$RUN_DIR/rollout_generations" -maxdepth 1 -type f -name '*.jsonl' -print -quit | grep -q .; then
    return 0
  fi
  return 1
}

TRAIN_CMD=(
  bash "$PROJECT_DIR/examples/minio3/run_real_train_pyvision_style_h200.sh"
  "data.train_max_samples=${TRAIN_MAX_SAMPLES}" \
  "data.val_max_samples=${VAL_MAX_SAMPLES}" \
  "data.filter_overlong_prompts_workers=${FILTER_OVERLONG_PROMPTS_WORKERS}" \
  "++ray_kwargs.ray_init.num_cpus=${RAY_NUM_CPUS}" \
  "+reward.custom_reward_function.reward_kwargs.self_judge_relaxed_answer=${SELF_JUDGE_RELAXED_ANSWER}" \
  "$@"
)

attempt=1
while true; do
  log_start_bytes=$(stat -c '%s' "$LOG_PATH" 2>/dev/null || echo 0)
  if "${TRAIN_CMD[@]}"; then
    exit 0
  fi
  status=$?

  if (( attempt >= MINIO3_RAY_STARTUP_RETRIES )) || training_has_started || ! ray_startup_failure_seen "$log_start_bytes"; then
    exit "$status"
  fi

  echo "[minio3-launch] early Ray startup failure detected; retrying attempt $((attempt + 1))/${MINIO3_RAY_STARTUP_RETRIES} after ${MINIO3_RAY_STARTUP_RETRY_DELAY_S}s"
  sleep "$MINIO3_RAY_STARTUP_RETRY_DELAY_S"
  attempt=$((attempt + 1))
done
